// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN232.Lab2.CoffeeStore.Repositories.Context;

#nullable disable

namespace PRN232.Lab2.CoffeeStore.Repositories.Migrations
{
    [DbContext(typeof(CoffeeStoreDbContext))]
    [Migration("20250922122146_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strong black coffee made by forcing steam through ground coffee beans",
                            Name = "Espresso"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso diluted with hot water",
                            Name = "Americano"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso with steamed milk",
                            Name = "Latte"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso with steamed milk and milk foam",
                            Name = "Cappuccino"
                        },
                        new
                        {
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso with chocolate and steamed milk",
                            Name = "Mocha"
                        },
                        new
                        {
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso marked with a small amount of milk foam",
                            Name = "Macchiato"
                        },
                        new
                        {
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso with microfoam milk",
                            Name = "Flat White"
                        },
                        new
                        {
                            CategoryId = 8,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee brewed with cold water for long hours",
                            Name = "Cold Brew"
                        },
                        new
                        {
                            CategoryId = 9,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coffee served chilled with ice",
                            Name = "Iced Coffee"
                        },
                        new
                        {
                            CategoryId = 10,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Espresso poured over vanilla ice cream",
                            Name = "Affogato"
                        },
                        new
                        {
                            CategoryId = 11,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Traditional green tea leaves brewed hot",
                            Name = "Green Tea"
                        },
                        new
                        {
                            CategoryId = 12,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Strong oxidized tea leaves",
                            Name = "Black Tea"
                        },
                        new
                        {
                            CategoryId = 13,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tea made from herbs and flowers",
                            Name = "Herbal Tea"
                        },
                        new
                        {
                            CategoryId = 14,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Partially oxidized tea with floral notes",
                            Name = "Oolong Tea"
                        },
                        new
                        {
                            CategoryId = 15,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spiced tea mixed with milk",
                            Name = "Chai Latte"
                        },
                        new
                        {
                            CategoryId = 16,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Green tea powder mixed with milk",
                            Name = "Matcha Latte"
                        },
                        new
                        {
                            CategoryId = 17,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet and creamy spiced iced tea",
                            Name = "Thai Iced Tea"
                        },
                        new
                        {
                            CategoryId = 18,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Black tea with milk, popular in bubble tea shops",
                            Name = "Milk Tea"
                        },
                        new
                        {
                            CategoryId = 19,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tea infused with fruits like peach or passion fruit",
                            Name = "Fruit Tea"
                        },
                        new
                        {
                            CategoryId = 20,
                            CreatedDate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fragrant green tea with jasmine aroma",
                            Name = "Jasmine Tea"
                        });
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A single shot of strong espresso",
                            IsActive = true,
                            Name = "Espresso Single",
                            Price = 2.50m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "A double shot of strong espresso",
                            IsActive = true,
                            Name = "Espresso Double",
                            Price = 3.50m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Espresso diluted with hot water",
                            IsActive = true,
                            Name = "Americano",
                            Price = 3.00m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3,
                            Description = "Espresso with steamed milk",
                            IsActive = true,
                            Name = "Latte",
                            Price = 4.00m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            Description = "Espresso with steamed milk and milk foam",
                            IsActive = true,
                            Name = "Cappuccino",
                            Price = 4.00m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 5,
                            Description = "Espresso with chocolate and steamed milk",
                            IsActive = true,
                            Name = "Mocha",
                            Price = 4.50m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6,
                            Description = "Espresso marked with a small amount of milk foam",
                            IsActive = true,
                            Name = "Macchiato",
                            Price = 3.00m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 7,
                            Description = "Espresso with microfoam milk",
                            IsActive = true,
                            Name = "Flat White",
                            Price = 4.00m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 8,
                            Description = "Coffee brewed with cold water for long hours",
                            IsActive = true,
                            Name = "Cold Brew",
                            Price = 4.50m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 9,
                            Description = "Coffee served chilled with ice",
                            IsActive = true,
                            Name = "Iced Coffee",
                            Price = 3.50m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 10,
                            Description = "Espresso poured over vanilla ice cream",
                            IsActive = true,
                            Name = "Affogato",
                            Price = 5.00m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 11,
                            Description = "Traditional green tea leaves brewed hot",
                            IsActive = true,
                            Name = "Green Tea",
                            Price = 2.00m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 12,
                            Description = "Strong oxidized tea leaves",
                            IsActive = true,
                            Name = "Black Tea",
                            Price = 2.00m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 13,
                            Description = "Tea made from herbs and flowers",
                            IsActive = true,
                            Name = "Herbal Tea",
                            Price = 2.50m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 14,
                            Description = "Partially oxidized tea with floral notes",
                            IsActive = true,
                            Name = "Oolong Tea",
                            Price = 2.50m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 15,
                            Description = "Spiced tea mixed with milk",
                            IsActive = true,
                            Name = "Chai Latte",
                            Price = 3.50m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 16,
                            Description = "Green tea powder mixed with milk",
                            IsActive = true,
                            Name = "Matcha Latte",
                            Price = 4.00m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 17,
                            Description = "Sweet and creamy spiced iced tea",
                            IsActive = true,
                            Name = "Thai Iced Tea",
                            Price = 3.50m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 18,
                            Description = "Black tea with milk, popular in bubble tea shops",
                            IsActive = true,
                            Name = "Milk Tea",
                            Price = 3.00m
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 19,
                            Description = "Tea infused with fruits like peach or passion fruit",
                            IsActive = true,
                            Name = "Fruit Tea",
                            Price = 3.00m
                        });
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Order", b =>
                {
                    b.HasOne("PRN232.Lab2.CoffeeStore.Repositories.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.OrderDetail", b =>
                {
                    b.HasOne("PRN232.Lab2.CoffeeStore.Repositories.Entity.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.Lab2.CoffeeStore.Repositories.Entity.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Payment", b =>
                {
                    b.HasOne("PRN232.Lab2.CoffeeStore.Repositories.Entity.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("PRN232.Lab2.CoffeeStore.Repositories.Entity.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Product", b =>
                {
                    b.HasOne("PRN232.Lab2.CoffeeStore.Repositories.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PRN232.Lab2.CoffeeStore.Repositories.Entity.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
